# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     questionDefinitionType.twig_extention:
          class: Ak\PollBundle\Twig\QuestionDefinitionTypeExtension
          public: false
          tags:
            - { name: twig.extension }
     hasEditableOptions.twig_extention:
          class: Ak\PollBundle\Twig\HasEditableOptionsExtension
          public: false
          tags:
            - { name: twig.extension }
     poll.repository.question_definition:
          class: Ak\PollBundle\Entity\QuestionDefinitionRepository
          factory_service: doctrine.orm.default_entity_manager
          factory_method: getRepository
          arguments:
              - Ak\PollBundle\Entity\QuestionDefinition
     poll.question_definitions_provider:
          class: Ak\PollBundle\Utils\Poll\QuestionDefinitionsProvider
          arguments:
              - @poll.repository.question_definition
     poll.question_definition_provider:
          class: Ak\PollBundle\Utils\Poll\QuestionDefinitionProvider
          arguments:
              - @poll.question_definitions_provider

     type.answer_type:
          class: Ak\PollBundle\Form\Type\AnswerType
          tags:
              - { name: form.type, alias: answer }
     validator.question_class:
          class: Ak\PollBundle\Validator\Constraints\QuestionClassValidator
          tags:
              - { name: validator.constraint_validator, alias: question_validator}

     validator.deal_class:
          class: Ak\PollBundle\Validator\Constraints\DealClassValidator
          tags:
              - { name: validator.constraint_validator, alias: deal_validator}

     type.registration_type:
          class: Ak\PollBundle\Form\Type\RegistrationType
          tags:
              - {name: form.type, alias: app_user_registration}
