<?php

namespace Ak\PollBundle\Entity;

/**
 * OptionDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionDefinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
