<?php

namespace Ak\PollBundle\Entity;

/**
 * PollDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollDefinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
