<?php

namespace Ak\PollBundle\Entity;

/**
 * QuestionDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionDefinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
