<?php

namespace Ak\PollBundle\Entity;
use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * QuestionDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionDefinitionRepository extends SortableRepository
{
    /**
     * @param PollDefinition $pollDefinition
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    public function getQuestionDefinitions(PollDefinition $pollDefinition){
        return $pollDefinition->getQuestionsDefinitions();
    }



}
